# From https://github.com/marketplace/actions/phpcs-drupal-check-with-annotations
name: Drupal coding standards
on: [push]

jobs:
  phpcs-drupal:
      name: Drupal coding standards
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: guix77/phpcs-drupal-action@v1.0.0
